Vagrant.configure("2") do |config|
    config.vm.define "postgres" do |postgres|
        postgres.vm.box = "ubuntu/focal64"
        postgres.vm.hostname = "postgres-to-share"
        config.vm.provision "ansible" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "postgres.yml"
            ansible.groups = {
              "postgres_servers" => ["postgres"]
            }
        end
    end
  end
  