mutation UPBMutation($id: ID!, $unpaidPrincipalBalance: Float) {
    loan1: update_Loan_async(
        id: $id
        input: {
            unpaidPrincipalBalance: $unpaidPrincipalBalance
        }
    ) {
        error
    }
}
