mutation createTickets {
    ticket1: add_Ticket_async(
        input: {
            passengerNameRecordCode: "ABC123",
            airlineCode: "AA",
            ticketNumber: "0014321900234",
            dateOfIssue: "2022-03-03",
            passenger: {
                firstName: "John",
                lastName: "Dough",
                dateOfBirth: "1972-05-06",
                frequentFlyerInformation: {
                    airlineCode: "AA",
                    frequentFlyerNumber: "5454321"
                }
            },
            ticketDocumentInfo: {
                primaryDocumentNumber: "4321900234",
                documentType: TKTT,
                fareBasis: "WE3MXUS",
                fareCalculationArea: ["BOS 6X DCA375.00END"]
            },
            coupons: [
                {
                    ticketNumber: "0014321900234",
                    ticketingDateOfIssue: "2022-03-03",
                    baggage: {
                        allowance: "2PC",
                        overAllowanceQualifier: "PC",
                        quantity: 1,
                        rate: {
                            amount: 50.00,
                            currency: "USD",
                            precision: 4
                        }
                    },
                    couponNumber: 1,
                    value: {
                        amount: 150.00,
                        currency: "USD",
                        precision: 5
                    },
                    classOfService: "W",
                    soldAirlineDesignator: "AA",
                    operatingAirlineDesignator: "AA",
                    soldDestinationCityCode: "DCA",
                    soldFlightDepartureDateTime: "2022-04-03T08:08:00Z",
                    soldFlightNumber: "1017",
                    soldOriginCityCode: "BOS"
                },
                {
                    ticketNumber: "0014321900234",
                    ticketingDateOfIssue: "2022-03-03",
                    baggage: {
                        allowance: "2PC",
                        overAllowanceQualifier: "PC",
                        quantity: 1,
                        rate: {
                            amount: 50.00,
                            currency: "USD",
                            precision: 4
                        }
                    },
                    couponNumber: 2,
                    value: {
                        amount: 225.00,
                        currency: "USD",
                        precision: 5
                    },
                    classOfService: "W",
                    soldAirlineDesignator: "AA",
                    operatingAirlineDesignator: "AA",
                    soldDestinationCityCode: "BOS",
                    soldFlightDepartureDateTime: "2022-04-04T18:08:00Z",
                    soldFlightNumber: "1219",
                    soldOriginCityCode: "DCA"
                }
            ],
            payments: [
                {
                    paymentType: CC,
                    paymentValue: {
                        amount: 445.20,
                        currency: "USD",
                        precision: 5
                    }
                }
            ],
            prices: {
                baseFareAmount: {
                    amount: 375.00,
                    currency: "USD",
                    precision: 5
                }
            },
            taxes: [
                {
                    code: "XT",
                    value: {
                        amount: 50.00,
                        currency: "USD",
                        precision: 4
                    }
                }
            ],
            fees: [
                {
                    code: XF,
                    value: {
                        amount: 11.20,
                        currency: "USD",
                        precision: 4
                    }
                },
                {
                    code: MF,
                    value: {
                        amount: 9.00,
                        currency: "USD",
                        precision: 3
                    }
                }
            ]
        },
        aclInput: {
            acl: [
                { principal: {nodes: ["AmericanNode"]}, operations: [ALL, UPDATE_ACL] },
            ]
        }
    ) {
        error
        result {
            _id
            _owner
            submissionTime
            transactionId
            version
        }
    },
    ticket2: add_Ticket_async(
        input: {
            passengerNameRecordCode: "EFG321",
            airlineCode: "AA",
            ticketNumber: "0010987654321",
            dateOfIssue: "2022-03-04",
            passenger: {
                firstName: "Juan",
                lastName: "Pasta",
                dateOfBirth: "1982-06-05",
                frequentFlyerInformation: {
                    airlineCode: "IA",
                    frequentFlyerNumber: "1234545"
                }
            },
            ticketDocumentInfo: {
                primaryDocumentNumber: "0987654321",
                documentType: TKTT,
                fareBasis: "WE3MXSP",
                fareCalculationArea: ["DCA 6X MAD575.00END"]
            },
            coupons: [
                {
                    ticketNumber: "0010987654321",
                    ticketingDateOfIssue: "2022-03-03",
                    baggage: {
                        allowance: "2PC",
                        overAllowanceQualifier: "PC",
                        quantity: 1,
                        rate: {
                            amount: 50.00,
                            currency: "USD",
                            precision: 4
                        }
                    },
                    couponNumber: 1,
                    value: {
                        amount: 250.00,
                        currency: "USD",
                        precision: 5
                    },
                    classOfService: "W",
                    soldAirlineDesignator: "AA",
                    operatingAirlineDesignator: "IA",
                    soldDestinationCityCode: "MAD",
                    soldFlightDepartureDateTime: "2022-04-03T11:00:00Z",
                    soldFlightNumber: "2233",
                    soldOriginCityCode: "DCA"
                },
                {
                    ticketNumber: "0010987654321",
                    ticketingDateOfIssue: "2022-03-03",
                    baggage: {
                        allowance: "2PC",
                        overAllowanceQualifier: "PC",
                        quantity: 1,
                        rate: {
                            amount: 50.00,
                            currency: "USD",
                            precision: 4
                        }
                    },
                    couponNumber: 2,
                    value: {
                        amount: 325.00,
                        currency: "USD",
                        precision: 5
                    },
                    classOfService: "W",
                    soldAirlineDesignator: "AA",
                    operatingAirlineDesignator: "IA",
                    soldDestinationCityCode: "DCA",
                    soldFlightDepartureDateTime: "2022-04-10T22:00:00Z",
                    soldFlightNumber: "9234",
                    soldOriginCityCode: "MAD"
                }
            ],
            payments: [
                {
                    paymentType: CC,
                    paymentValue: {
                        amount: 645.20,
                        currency: "USD",
                        precision: 5
                    }
                }
            ],
            prices: {
                baseFareAmount: {
                    amount: 575.00,
                    currency: "USD",
                    precision: 5
                }
            },
            taxes: [
                {
                    code: "XT",
                    value: {
                        amount: 50.00,
                        currency: "USD",
                        precision: 4
                    }
                }
            ],
            fees: [
                {
                    code: XF,
                    value: {
                        amount: 11.20,
                        currency: "USD",
                        precision: 4
                    }
                },
                {
                    code: MF,
                    value: {
                        amount: 9.00,
                        currency: "USD",
                        precision: 3
                    }
                }
            ]
        },
        aclInput: {
            acl: [
                { principal: {nodes: ["AmericanNode"]}, operations: [ALL, UPDATE_ACL] },
                { principal: {nodes: ["IberiaNode"]}, path: "ticketDocumentInfo.primaryDocumentNumber", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "ticketDocumentInfo.documentType", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "passengerNameRecordCode", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "airlineCode", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "ticketNumber", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "dateOfIssue", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "passenger", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "coupons", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "payments", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "prices", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "taxes", operations: [READ] },
                { principal: {nodes: ["IberiaNode"]}, path: "fees", operations: [READ] }
            ]
        }
    )
    {
        error
        result {
            _id
            _owner
            submissionTime
            transactionId
            version
        }
    }
}
