mutation createTickets {
    ticket1: add_Ticket(
        input: {
            passengerNameRecordCode: "XYZ123",
            airlineCode: "IA",
            ticketNumber: "0755463728190",
            dateOfIssue: "2022-05-05",
            passenger: {
                firstName: "John",
                lastName: "Dough",
                dateOfBirth: "1972-05-06",
                frequentFlyerInformation: {
                    airlineCode: "IA",
                    frequentFlyerNumber: "999888777"
                }
            },
            ticketDocumentInfo: {
                primaryDocumentNumber: "5463728190",
                documentType: TKTT,
                fareBasis: "JE3MXSP",
                fareCalculationArea: ["SVQ 6X MAD375.00EUREND"]
            },
            coupons: [
                {
                    ticketNumber: "0754321900234",
                    ticketingDateOfIssue: "2022-05-05",
                    baggage: {
                        allowance: "2PC",
                        overAllowanceQualifier: "PC",
                        quantity: 1,
                        rate: {
                            amount: 50.00,
                            currency: "EUR",
                            precision: 4
                        }
                    },
                    couponNumber: 1,
                    value: {
                        amount: 150.00,
                        currency: "EUR",
                        precision: 5
                    },
                    classOfService: "J",
                    soldAirlineDesignator: "IA",
                    operatingAirlineDesignator: "IA",
                    soldDestinationCityCode: "MAD",
                    soldFlightDepartureDateTime: "2022-05-12T20:00:00Z",
                    soldFlightNumber: "333",
                    soldOriginCityCode: "SVQ"
                },
                {
                    ticketNumber: "0754321900234",
                    ticketingDateOfIssue: "2022-05-05",
                    baggage: {
                        allowance: "2PC",
                        overAllowanceQualifier: "PC",
                        quantity: 1,
                        rate: {
                            amount: 50.00,
                            currency: "USD",
                            precision: 4
                        }
                    },
                    couponNumber: 1,
                    value: {
                        amount: 150.00,
                        currency: "EUR",
                        precision: 5
                    },
                    classOfService: "J",
                    soldAirlineDesignator: "IA",
                    operatingAirlineDesignator: "IA",
                    soldDestinationCityCode: "SVQ",
                    soldFlightDepartureDateTime: "2022-05-15T20:00:00Z",
                    soldFlightNumber: "333",
                    soldOriginCityCode: "MAD"
                },
            ],
            payments: [
                {
                    paymentType: CC,
                    paymentValue: {
                        amount: 445.20,
                        currency: "EUR",
                        precision: 5
                    }
                }
            ],
            prices: {
                baseFareAmount: {
                    amount: 375.00,
                    currency: "EUR",
                    precision: 5
                }
            },
            taxes: [
                {
                    code: "XT",
                    value: {
                        amount: 50.00,
                        currency: "EUR",
                        precision: 4
                    }
                }
            ],
            fees: [
                {
                    code: XF,
                    value: {
                        amount: 11.20,
                        currency: "EUR",
                        precision: 4
                    }
                },
                {
                    code: MF,
                    value: {
                        amount: 9.00,
                        currency: "EUR",
                        precision: 3
                    }
                }
            ]
        },
        aclInput: {
            acl: [
                { principal: {nodes: ["IberiaNode"]}, operations: [ALL, UPDATE_ACL] },
            ]
        },
        syncMode: ASYNC) {
        transaction {
            _id
            _owner
            submissionTime
            transactionId
            version
        }
    },
    ticket2: add_Ticket(
        input: {
            passengerNameRecordCode: "ZYXWV3",
            airlineCode: "IA",
            ticketNumber: "0754321905432",
            dateOfIssue: "2022-04-24",
            passenger: {
                firstName: "Juan",
                lastName: "Pasta",
                dateOfBirth: "1982-06-05",
                frequentFlyerInformation: {
                    airlineCode: "IA",
                    frequentFlyerNumber: "1234545"
                }
            },
            ticketDocumentInfo: {
                primaryDocumentNumber: "4321905432",
                documentType: TKTT,
                fareBasis: "JE3MXSP",
                fareCalculationArea: ["DCA 6X MAD575.00EUREND"]
            },
            coupons: [
                {
                    ticketNumber: "0754321905432",
                    ticketingDateOfIssue: "2022-04-24",
                    baggage: {
                        allowance: "2PC",
                        overAllowanceQualifier: "PC",
                        quantity: 1,
                        rate: {
                            amount: 50.00,
                            currency: "EUR",
                            precision: 4
                        }
                    },
                    couponNumber: 1,
                    value: {
                        amount: 250.00,
                        currency: "EUR",
                        precision: 5
                    },
                    classOfService: "J",
                    soldAirlineDesignator: "IA",
                    operatingAirlineDesignator: "AA",
                    soldDestinationCityCode: "MAD",
                    soldFlightDepartureDateTime: "2022-05-01T13:00:00Z",
                    soldFlightNumber: "2233",
                    soldOriginCityCode: "DCA"
                },
                {
                    ticketNumber: "0014321900234",
                    ticketingDateOfIssue: "2022-03-03",
                    baggage: {
                        allowance: "2PC",
                        overAllowanceQualifier: "PC",
                        quantity: 1,
                        rate: {
                            amount: 50.00,
                            currency: "EUR",
                            precision: 4
                        }
                    },
                    couponNumber: 2,
                    value: {
                        amount: 325.00,
                        currency: "EUR",
                        precision: 5
                    },
                    classOfService: "J",
                    soldAirlineDesignator: "IA",
                    operatingAirlineDesignator: "AA",
                    soldDestinationCityCode: "DCA",
                    soldFlightDepartureDateTime: "2022-05-10T22:00:00Z",
                    soldFlightNumber: "9234",
                    soldOriginCityCode: "MAD"
                }
            ],
            payments: [
                {
                    paymentType: CC,
                    paymentValue: {
                        amount: 645.20,
                        currency: "EUR",
                        precision: 5
                    }
                }
            ],
            prices: {
                baseFareAmount: {
                    amount: 575.00,
                    currency: "EUR",
                    precision: 5
                }
            },
            taxes: [
                {
                    code: "XT",
                    value: {
                        amount: 50.00,
                        currency: "EUR",
                        precision: 4
                    }
                }
            ],
            fees: [
                {
                    code: XF,
                    value: {
                        amount: 11.20,
                        currency: "EUR",
                        precision: 4
                    }
                },
                {
                    code: MF,
                    value: {
                        amount: 9.00,
                        currency: "EUR",
                        precision: 3
                    }
                }
            ]
        },
        aclInput: {
            acl: [
                { principal: {nodes: ["IberiaNode"]}, operations: [ALL, UPDATE_ACL] },
                { principal: {nodes: ["AmericanNode"]}, path: "ticketDocumentInfo.primaryDocumentNumber", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "ticketDocumentInfo.documentType", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "passengerNameRecordCode", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "airlineCode", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "ticketNumber", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "dateOfIssue", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "passenger", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "coupons", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "payments", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "prices", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "taxes", operations: [READ] },
                { principal: {nodes: ["AmericanNode"]}, path: "fees", operations: [READ] }
            ]
        },
        syncMode: ASYNC){
        transaction {
            _id
            _owner
            submissionTime
            transactionId
            version
        }
    }
}
