mutation DelinquencyMutation($id: ID!, $delinquentPercent: Float, $latePercent: Float) {
    update_LoanPortfolio(
        id: $id
        input: {
            delinquentPercent: $delinquentPercent,
            latePercent: $latePercent
        }
        syncMode: ASYNC
    ) {
        __typename
    }
}